---
- name: Download APT key
  ansible.builtin.get_url:
    url: "{{ docker_key_url }}"
    dest: "{{ docker_key_path }}"
    mode: '0644'

- name: Get package architecture
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: package_architecture

- name: Add APT repository
  ansible.builtin.apt_repository:
    repo: >
        deb
        [arch={{ package_architecture.stdout }} signed-by={{ docker_key_path }}]
        {{ docker_repo_url }}
        {{ ansible_distribution_release }}
        stable
    filename: "docker"
    state: present

- name: Install packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
