---
- name: Check if Docker Swarm is inactive
  ansible.builtin.shell: >
    docker info --format {{ '{{.Swarm.LocalNodeState}}' }} | grep -qw inactive
  ignore_errors: yes
  failed_when: no
  changed_when: no
  register: docker_swarm_is_inactive

- name: Initialize Docker Swarm when inactive
  ansible.builtin.command: docker swarm init
  when: docker_swarm_is_inactive.rc == 0
