---
- name: Check if Docker Swarm is inactive
  shell: >
    docker info --format {{ '{{.Swarm.LocalNodeState}}' }} | grep -qw inactive
  ignore_errors: yes
  failed_when: no
  changed_when: no
  register: docker_swarm_is_inactive

- name: Initialise Docker Swarm when inactive
  command: docker swarm init
  when: docker_swarm_is_inactive.rc == 0
